name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: ServiceConnection
    value: AzureServiceConnection

stages:
  - stage: Build_Static
    displayName: Build Static Website
    jobs:
      - job: Build
        displayName: Build Vue
        steps:
          - script: npm ci
          - script: npm run build
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: ui
              publishLocation: pipeline
  - stage: Release_DEV
    displayName: Release - DEV
    jobs:
      - deployment: Deployment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Copy to Azure Storage
                  inputs:
                    azureSubscription: $(ServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az storage blob upload-batch -d '$web' --account-name adfcsvcosmosdev -s $(Pipeline.Workspace)/ui --auth-mode login