name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: ServiceConnection
    value: AzureServiceConnection

stages:
  - stage: Build_Static
    displayName: Build Static Website
    jobs:
      - job: Build
        displayName: Build Vue
        steps:
          - script: npm ci
          - script: npm run build
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: dist
              publishLocation: pipeline
  - stage: Release_DEV
    displayName: Release - DEV
    jobs:
      - deployment: Deployment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFileCopy@4
                  displayName: Copy to Azure Storage
                  inputs:
                    SourcePath: $(Build.StagingDirectory)/dist
                    azureSubscription: "$(ServiceConnection)"
                    Destination: AzureBlob
                    storage: adfcsvcosmosdev
                    ContainerName: "$web"