name: $(Build.DefinitionName)-$(Date:yyyyMMdd)-$(BuildID)

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_Static
    displayName: Build Static Website
    jobs:
      - job: Build
        displayName: Build Vue
        steps:
          - script: npm ci
          - script: npm run build
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: ui
              publishLocation: pipeline
  - stage: Release_DEV
    displayName: Release - DEV
    variables:
      - group: dev
    jobs:
      - deployment: Deployment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureStaticWebApp@0
                  displayName: Deploy Static Website
                  inputs:
                    app_build_command: npm run build
                    app_location: /
                    output_location: dist
                    azure_static_web_apps_api_token: $(StaticWebsiteDeploymentToken)